kind: pipeline
type: docker
name: default
workspace:
  path: /usr/src/app

steps:
  #  - name: greeting
  #    image: alpine
  #    commands:
  #      - echo hello
  #      - echo world
  - name: test
    image: golang
    commands:
      - go test
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: chenly2114/drone-ci-demo