kind: pipeline
type: docker
name: run
workspace:
  path: /usr/src/app

steps:
  - name: test
    image: golang
    commands:
      - go test
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: chenly2114/drone-ci-demo
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: host_username
      password:
        from_secret: host_password
      port: 22
      script:
        - echo hello
        - echo world