kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang
    commands:
      - go test
      - go build
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
