kind: pipeline
type: docker
name: default

steps:
  #  - name: greeting
  #    image: alpine
  #    commands:
  #      - echo hello
  #      - echo world
  - name: test
    image: golang
    commands:
      - go test
      - go build
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: chenly2114/drone-ci-demo